# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/psh/work/project_9/project_9.srcs/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/soc_btn_fnd_axi_smc_0.xci
# IP: The module: 'soc_btn_fnd_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/bd_67cd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_0/bd_67cd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_1/bd_67cd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_2/bd_67cd_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_3/bd_67cd_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_4/bd_67cd_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_5/bd_67cd_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_6/bd_67cd_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_7/bd_67cd_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_8/bd_67cd_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_9/bd_67cd_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_10/bd_67cd_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_11/bd_67cd_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_12/bd_67cd_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_13/bd_67cd_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_14/bd_67cd_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_15/bd_67cd_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_16/bd_67cd_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_17/bd_67cd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_18/bd_67cd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_19/bd_67cd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_20/bd_67cd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_21/bd_67cd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_22/bd_67cd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_23/bd_67cd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_24/bd_67cd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_25/bd_67cd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_26/bd_67cd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_27/bd_67cd_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_28/bd_67cd_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_29/bd_67cd_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_30/bd_67cd_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_31/bd_67cd_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_32/bd_67cd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_33/bd_67cd_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_34/bd_67cd_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_35/bd_67cd_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_36/bd_67cd_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_37/bd_67cd_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_38/bd_67cd_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_39/bd_67cd_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_40/bd_67cd_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_41/bd_67cd_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_42/bd_67cd_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_43/bd_67cd_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_44/bd_67cd_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_45/bd_67cd_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_46/bd_67cd_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_1/bd_67cd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_1/bd_67cd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_2/bd_67cd_arinsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_3/bd_67cd_rinsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_4/bd_67cd_awinsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_5/bd_67cd_winsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_6/bd_67cd_binsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_7/bd_67cd_aroutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_8/bd_67cd_routsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_9/bd_67cd_awoutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_10/bd_67cd_woutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_11/bd_67cd_boutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_12/bd_67cd_arni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_13/bd_67cd_rni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_14/bd_67cd_awni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_15/bd_67cd_wni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_16/bd_67cd_bni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_20/bd_67cd_s00a2s_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_21/bd_67cd_sarn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_22/bd_67cd_srn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_23/bd_67cd_sawn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_24/bd_67cd_swn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_25/bd_67cd_sbn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_26/bd_67cd_m00s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_27/bd_67cd_m00arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_28/bd_67cd_m00rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_29/bd_67cd_m00awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_30/bd_67cd_m00wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_31/bd_67cd_m00bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_33/bd_67cd_m01s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_34/bd_67cd_m01arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_35/bd_67cd_m01rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_36/bd_67cd_m01awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_37/bd_67cd_m01wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_38/bd_67cd_m01bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_40/bd_67cd_m02s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_41/bd_67cd_m02arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_42/bd_67cd_m02rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_43/bd_67cd_m02awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_44/bd_67cd_m02wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_45/bd_67cd_m02bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/psh/work/project_9/project_9.srcs/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/soc_btn_fnd_axi_smc_0.xci
# IP: The module: 'soc_btn_fnd_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/bd_67cd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_0/bd_67cd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_1/bd_67cd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_2/bd_67cd_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_3/bd_67cd_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_4/bd_67cd_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_5/bd_67cd_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_6/bd_67cd_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_7/bd_67cd_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_8/bd_67cd_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_9/bd_67cd_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_10/bd_67cd_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_11/bd_67cd_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_12/bd_67cd_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_13/bd_67cd_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_14/bd_67cd_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_15/bd_67cd_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_16/bd_67cd_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_17/bd_67cd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_18/bd_67cd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_19/bd_67cd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_20/bd_67cd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_21/bd_67cd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_22/bd_67cd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_23/bd_67cd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_24/bd_67cd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_25/bd_67cd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_26/bd_67cd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_27/bd_67cd_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_28/bd_67cd_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_29/bd_67cd_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_30/bd_67cd_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_31/bd_67cd_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_32/bd_67cd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_33/bd_67cd_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_34/bd_67cd_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_35/bd_67cd_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_36/bd_67cd_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_37/bd_67cd_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_38/bd_67cd_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_39/bd_67cd_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_40/bd_67cd_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_41/bd_67cd_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_42/bd_67cd_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_43/bd_67cd_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_44/bd_67cd_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_45/bd_67cd_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_46/bd_67cd_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_1/bd_67cd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_1/bd_67cd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_2/bd_67cd_arinsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_3/bd_67cd_rinsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_4/bd_67cd_awinsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_5/bd_67cd_winsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_6/bd_67cd_binsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_7/bd_67cd_aroutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_8/bd_67cd_routsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_9/bd_67cd_awoutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_10/bd_67cd_woutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_11/bd_67cd_boutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_12/bd_67cd_arni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_13/bd_67cd_rni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_14/bd_67cd_awni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_15/bd_67cd_wni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_16/bd_67cd_bni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_20/bd_67cd_s00a2s_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_21/bd_67cd_sarn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_22/bd_67cd_srn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_23/bd_67cd_sawn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_24/bd_67cd_swn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_25/bd_67cd_sbn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_26/bd_67cd_m00s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_27/bd_67cd_m00arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_28/bd_67cd_m00rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_29/bd_67cd_m00awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_30/bd_67cd_m00wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_31/bd_67cd_m00bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_33/bd_67cd_m01s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_34/bd_67cd_m01arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_35/bd_67cd_m01rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_36/bd_67cd_m01awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_37/bd_67cd_m01wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_38/bd_67cd_m01bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_40/bd_67cd_m02s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_41/bd_67cd_m02arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_42/bd_67cd_m02rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_43/bd_67cd_m02awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_44/bd_67cd_m02wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/bd_0/ip/ip_45/bd_67cd_m02bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
