# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/psh/work/project_9/project_9.srcs/sources_1/bd/soc_hello/ip/soc_hello_dlmb_bram_if_cntlr_1/soc_hello_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'soc_hello_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_hello/ip/soc_hello_dlmb_bram_if_cntlr_1/soc_hello_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/psh/work/project_9/project_9.srcs/sources_1/bd/soc_hello/ip/soc_hello_dlmb_bram_if_cntlr_1/soc_hello_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'soc_hello_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_hello/ip/soc_hello_dlmb_bram_if_cntlr_1/soc_hello_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
