# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/work/Basys-3-Master.xdc

# IP: ip/xadc_joystic/xadc_joystic.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_joystic || ORIG_REF_NAME==xadc_joystic} -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/ip/xadc_joystic/xadc_joystic_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/ip/xadc_joystic/xadc_joystic.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_joystic || ORIG_REF_NAME==xadc_joystic} -quiet] {/inst } ]/inst ] -quiet] -quiet
