# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/work/Basys-3-Master.xdc

# Block Designs: bd/soc_btn_fnd/soc_btn_fnd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd || ORIG_REF_NAME==soc_btn_fnd} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_proc_sys_reset_0_0/soc_btn_fnd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_btn_fnd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_clk_wiz_0/soc_btn_fnd_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_clk_wiz_0 || ORIG_REF_NAME==soc_btn_fnd_clk_wiz_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_microblaze_riscv_0_0/soc_btn_fnd_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_btn_fnd_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_dlmb_v10_0/soc_btn_fnd_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_dlmb_v10_0 || ORIG_REF_NAME==soc_btn_fnd_dlmb_v10_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_ilmb_v10_0/soc_btn_fnd_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_ilmb_v10_0 || ORIG_REF_NAME==soc_btn_fnd_ilmb_v10_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_dlmb_bram_if_cntlr_0/soc_btn_fnd_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_btn_fnd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_ilmb_bram_if_cntlr_0/soc_btn_fnd_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_btn_fnd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_lmb_bram_0/soc_btn_fnd_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_lmb_bram_0 || ORIG_REF_NAME==soc_btn_fnd_lmb_bram_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_mdm_1_0/soc_btn_fnd_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_mdm_1_0 || ORIG_REF_NAME==soc_btn_fnd_mdm_1_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_axi_uartlite_0_0/soc_btn_fnd_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_axi_uartlite_0_0 || ORIG_REF_NAME==soc_btn_fnd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_axi_smc_0/soc_btn_fnd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_axi_smc_0 || ORIG_REF_NAME==soc_btn_fnd_axi_smc_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_0_0/soc_btn_fnd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_axi_gpio_0_0 || ORIG_REF_NAME==soc_btn_fnd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_1_0/soc_btn_fnd_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_btn_fnd_axi_gpio_1_0 || ORIG_REF_NAME==soc_btn_fnd_axi_gpio_1_0} -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_btn_fnd/soc_btn_fnd_ooc.xdc
