# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/work/Basys-3-Master.xdc

# Block Designs: bd/soc_stop_watch/soc_stop_watch.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch || ORIG_REF_NAME==soc_stop_watch} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_proc_sys_reset_0_0/soc_stop_watch_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_stop_watch_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_clk_wiz_0/soc_stop_watch_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_clk_wiz_0 || ORIG_REF_NAME==soc_stop_watch_clk_wiz_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_microblaze_riscv_0_0/soc_stop_watch_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_stop_watch_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_dlmb_v10_0/soc_stop_watch_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_dlmb_v10_0 || ORIG_REF_NAME==soc_stop_watch_dlmb_v10_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_ilmb_v10_0/soc_stop_watch_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_ilmb_v10_0 || ORIG_REF_NAME==soc_stop_watch_ilmb_v10_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_dlmb_bram_if_cntlr_0/soc_stop_watch_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_stop_watch_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_ilmb_bram_if_cntlr_0/soc_stop_watch_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_stop_watch_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_lmb_bram_0/soc_stop_watch_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_lmb_bram_0 || ORIG_REF_NAME==soc_stop_watch_lmb_bram_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_mdm_1_0/soc_stop_watch_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_mdm_1_0 || ORIG_REF_NAME==soc_stop_watch_mdm_1_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_axi_uartlite_0_0/soc_stop_watch_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_uartlite_0_0 || ORIG_REF_NAME==soc_stop_watch_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/soc_stop_watch_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_smc_0 || ORIG_REF_NAME==soc_stop_watch_axi_smc_0} -quiet] -quiet

# Block Designs: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/bd_b74d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_0/bd_b74d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_1/bd_b74d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_2/bd_b74d_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_3/bd_b74d_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_4/bd_b74d_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_5/bd_b74d_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_6/bd_b74d_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_7/bd_b74d_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_8/bd_b74d_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_9/bd_b74d_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_10/bd_b74d_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_11/bd_b74d_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_12/bd_b74d_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_13/bd_b74d_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_14/bd_b74d_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_15/bd_b74d_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_16/bd_b74d_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_17/bd_b74d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_18/bd_b74d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_19/bd_b74d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_20/bd_b74d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_21/bd_b74d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_22/bd_b74d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_23/bd_b74d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_24/bd_b74d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_25/bd_b74d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_26/bd_b74d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_27/bd_b74d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_28/bd_b74d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_29/bd_b74d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_30/bd_b74d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_31/bd_b74d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_32/bd_b74d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_33/bd_b74d_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_34/bd_b74d_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_35/bd_b74d_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_36/bd_b74d_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_37/bd_b74d_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_38/bd_b74d_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_39/bd_b74d_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_40/bd_b74d_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_41/bd_b74d_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_42/bd_b74d_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_43/bd_b74d_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_44/bd_b74d_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_45/bd_b74d_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_46/bd_b74d_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_47/bd_b74d_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_48/bd_b74d_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_49/bd_b74d_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_50/bd_b74d_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_51/bd_b74d_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_52/bd_b74d_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_53/bd_b74d_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/soc_stop_watch/ip/soc_stop_watch_myip_stop_watch_0_0/soc_stop_watch_myip_stop_watch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_myip_stop_watch_0_0 || ORIG_REF_NAME==soc_stop_watch_myip_stop_watch_0_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_axi_gpio_0_0/soc_stop_watch_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_gpio_0_0 || ORIG_REF_NAME==soc_stop_watch_axi_gpio_0_0} -quiet] -quiet

# IP: bd/soc_stop_watch/ip/soc_stop_watch_axi_iic_0_0/soc_stop_watch_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_iic_0_0 || ORIG_REF_NAME==soc_stop_watch_axi_iic_0_0} -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_proc_sys_reset_0_0/soc_stop_watch_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_stop_watch_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_proc_sys_reset_0_0/soc_stop_watch_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_stop_watch_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_clk_wiz_0/soc_stop_watch_clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_clk_wiz_0 || ORIG_REF_NAME==soc_stop_watch_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_clk_wiz_0/soc_stop_watch_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_clk_wiz_0 || ORIG_REF_NAME==soc_stop_watch_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_clk_wiz_0/soc_stop_watch_clk_wiz_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_microblaze_riscv_0_0/soc_stop_watch_microblaze_riscv_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_stop_watch_microblaze_riscv_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_microblaze_riscv_0_0/soc_stop_watch_microblaze_riscv_0_0_ooc_debug.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_lmb_bram_0/soc_stop_watch_lmb_bram_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_mdm_1_0/soc_stop_watch_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_mdm_1_0 || ORIG_REF_NAME==soc_stop_watch_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_mdm_1_0/soc_stop_watch_mdm_1_0_ooc_trace.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_uartlite_0_0/soc_stop_watch_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_uartlite_0_0 || ORIG_REF_NAME==soc_stop_watch_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_uartlite_0_0/soc_stop_watch_axi_uartlite_0_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_uartlite_0_0/soc_stop_watch_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_uartlite_0_0 || ORIG_REF_NAME==soc_stop_watch_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_1/bd_b74d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_1/bd_b74d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_2/bd_b74d_arinsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_3/bd_b74d_rinsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_4/bd_b74d_awinsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_5/bd_b74d_winsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_6/bd_b74d_binsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_7/bd_b74d_aroutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_8/bd_b74d_routsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_9/bd_b74d_awoutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_10/bd_b74d_woutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_11/bd_b74d_boutsw_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_12/bd_b74d_arni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_13/bd_b74d_rni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_14/bd_b74d_awni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_15/bd_b74d_wni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_16/bd_b74d_bni_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_20/bd_b74d_s00a2s_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_21/bd_b74d_sarn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_22/bd_b74d_srn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_23/bd_b74d_sawn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_24/bd_b74d_swn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_25/bd_b74d_sbn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_26/bd_b74d_m00s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_27/bd_b74d_m00arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_28/bd_b74d_m00rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_29/bd_b74d_m00awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_30/bd_b74d_m00wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_31/bd_b74d_m00bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_33/bd_b74d_m01s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_34/bd_b74d_m01arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_35/bd_b74d_m01rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_36/bd_b74d_m01awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_37/bd_b74d_m01wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_38/bd_b74d_m01bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_40/bd_b74d_m02s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_41/bd_b74d_m02arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_42/bd_b74d_m02rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_43/bd_b74d_m02awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_44/bd_b74d_m02wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_45/bd_b74d_m02bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_47/bd_b74d_m03s2a_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_48/bd_b74d_m03arn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_49/bd_b74d_m03rn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_50/bd_b74d_m03awn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_51/bd_b74d_m03wn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_52/bd_b74d_m03bn_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_smc_0 || ORIG_REF_NAME==soc_stop_watch_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_gpio_0_0/soc_stop_watch_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_gpio_0_0 || ORIG_REF_NAME==soc_stop_watch_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_gpio_0_0/soc_stop_watch_axi_gpio_0_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_gpio_0_0/soc_stop_watch_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_gpio_0_0 || ORIG_REF_NAME==soc_stop_watch_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_iic_0_0/soc_stop_watch_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_stop_watch_axi_iic_0_0 || ORIG_REF_NAME==soc_stop_watch_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_iic_0_0/soc_stop_watch_axi_iic_0_0_ooc.xdc

# XDC: /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/soc_stop_watch_ooc.xdc
