# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/psh/work/project_9/project_9.runs/synth_1/soc_stop_watch_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/psh/work/project_9/project_9.cache/wt [current_project]
set_property parent.project_path /home/psh/work/project_9/project_9.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/psh/.Xilinx/Vivado/2024.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/psh/work/ip_repo/myip_stop_watch_1_0
  /home/psh/work/ip_repo/myip_iic_txtlcd_1_0
  /home/psh/work/ip_repo/myip_dht11_1_0
  /home/psh/work/ip_repo/myip_fnd_1_0
  /home/psh/work/ip_repo/myip_fnd_1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/psh/work/project_9/project_9.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/hdl/soc_stop_watch_wrapper.v
add_files /home/psh/work/project_9/project_9.srcs/sources_1/bd/soc_stop_watch/soc_stop_watch.bd
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_proc_sys_reset_0_0/soc_stop_watch_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_proc_sys_reset_0_0/soc_stop_watch_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_clk_wiz_0/soc_stop_watch_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_clk_wiz_0/soc_stop_watch_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_clk_wiz_0/soc_stop_watch_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_microblaze_riscv_0_0/soc_stop_watch_microblaze_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_microblaze_riscv_0_0/soc_stop_watch_microblaze_riscv_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_lmb_bram_0/soc_stop_watch_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_mdm_1_0/soc_stop_watch_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_mdm_1_0/soc_stop_watch_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_uartlite_0_0/soc_stop_watch_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_uartlite_0_0/soc_stop_watch_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_uartlite_0_0/soc_stop_watch_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_1/bd_b74d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_1/bd_b74d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_2/bd_b74d_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_3/bd_b74d_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_4/bd_b74d_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_5/bd_b74d_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_6/bd_b74d_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_7/bd_b74d_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_8/bd_b74d_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_9/bd_b74d_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_10/bd_b74d_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_11/bd_b74d_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_12/bd_b74d_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_13/bd_b74d_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_14/bd_b74d_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_15/bd_b74d_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_16/bd_b74d_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_20/bd_b74d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_21/bd_b74d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_22/bd_b74d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_23/bd_b74d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_24/bd_b74d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_25/bd_b74d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_26/bd_b74d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_27/bd_b74d_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_28/bd_b74d_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_29/bd_b74d_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_30/bd_b74d_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_31/bd_b74d_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_33/bd_b74d_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_34/bd_b74d_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_35/bd_b74d_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_36/bd_b74d_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_37/bd_b74d_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_38/bd_b74d_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_40/bd_b74d_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_41/bd_b74d_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_42/bd_b74d_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_43/bd_b74d_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_44/bd_b74d_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_45/bd_b74d_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_47/bd_b74d_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_48/bd_b74d_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_49/bd_b74d_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_50/bd_b74d_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_51/bd_b74d_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/bd_0/ip/ip_52/bd_b74d_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_gpio_0_0/soc_stop_watch_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_gpio_0_0/soc_stop_watch_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_gpio_0_0/soc_stop_watch_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_iic_0_0/soc_stop_watch_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_axi_iic_0_0/soc_stop_watch_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/soc_stop_watch_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/psh/work/project_9/project_9.gen/sources_1/bd/soc_stop_watch/ip/soc_stop_watch_microblaze_riscv_0_0/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/psh/work/project_9/project_9.srcs/constrs_1/imports/work/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/psh/work/project_9/project_9.srcs/constrs_1/imports/work/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/psh/work/project_9/project_9.srcs/utils_1/imports/synth_1/dht11_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top soc_stop_watch_wrapper -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_stop_watch_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file soc_stop_watch_wrapper_utilization_synth.rpt -pb soc_stop_watch_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
